app/models/post.py
from datetime import datetime

from app import db


class Post(db.Model):

    __tablename__ = 'Posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    body = db.Column(db.Text)
    time_created = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    time_modified = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey('Users.id'))
    comments = db.relationship('PostComment', backref='post', lazy='dynamic')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def __repr__(self):
        return '<Post {0}>'.format(self.title)

app/forms/post.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField,\
    SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp


class NewPostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired(), Length(1, 128)])
    body = TextAreaField('正文', validators=[DataRequired()])
    submit = SubmitField('发表文章')


class EditPostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired(), Length(1, 128)])
    body = TextAreaField('正文', validators=[DataRequired()])
    submit = SubmitField('提交修改')

app/routes/post.py
from flask import (
    render_template,
    flash,
    redirect,
    url_for,
    request,
    Blueprint,
)
from flask_login import (
    current_user,
    login_user,
    logout_user,
    login_required,
)
from app import db
from app.forms.post import NewPostForm, EditPostForm
from app.forms.comment import PostCommentForm
from app.models.role import Permission
from app.models.user import User
from app.models.post import Post
from app.models.comment import PostComment


from app.models.role import Permission

main = Blueprint('post', __name__)


# 将 Permission 类加入模板上下文
@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)


@main.route('/<int:id>', methods=['GET', 'POST'])
def view_post(id):
    post = Post.query.get_or_404(id)
    form = PostCommentForm()
    comments = post.comments.order_by(PostComment.time_created.asc())
    if request.method == 'POST':
        if form.validate_on_submit():
            comment = PostComment(
                body=form.body.data,
                post=post,
                author=current_user._get_current_object(),
            )
            db.session.add(comment)
            db.session.commit()
            flash('您已发表评论')
            return redirect(url_for('.view_post', id=id))
    else:
        return render_template('post/view_post.html', id=id, post=post, comments=comments, form=form)


@main.route('/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = NewPostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            post = Post(
                title=form.title.data,
                body=form.title.data,
                author=current_user._get_current_object(),
            )
            db.session.add(post)
            db.session.commit()
            flash('恭喜, 您已成功发表文章!')
            return redirect(url_for('.view_post', id=post.id))
        else:
            flash('您提交的表格有误, 请修改后重新发表!')
            return redirect(url_for('.new_post', form=form))
    else:
        return render_template('post/new_post.html', form=form)


@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    form = EditPostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            post.title = form.title.data
            post.body = form.body.data
            db.session.add(post)
            db.session.commit()
            flash('恭喜, 您已成功修改文章!')
            return redirect(url_for('.view_post', id=post.id))
        else:
            flash('您提交的表格有误, 请修改后重新发表!')
            return redirect(url_for('.edit_post', form=form))
    else:
        form.title.data = post.title
        form.body.data = post.body
        return render_template('post/edit_post.html', form=form)


@main.route('/delete/<int:id>')
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()
    comments = post.comments
    for comment in comments:
        db.session.delete(comment)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('home.index'))

app/routes/user.py
from flask import (
    render_template,
    redirect,
    url_for,
    request,
    flash,
    Blueprint,
)
from flask_login import (
    current_user,
    login_user,
    logout_user,
    login_required,
)
from app import db
from app.forms.user import (
    LoginForm,
    RegistrationForm,
    SettingUsernameForm,
    SettingPasswordForm,
    SettingSignatureForm,
)
from app.models.user import User
from app.models.post import Post


main = Blueprint('user', __name__)


@main.route('/login', methods=['GET', 'POST'])
def login():
    # 用户已登录
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    # 用户未登录
    else:
        form = LoginForm()
        if request.method == 'POST':
            if form.validate_on_submit():
                user = User.query.filter_by(username=form.username.data).first()
                if user is not None and user.verify_password(form.password.data):
                    login_user(user, remember=form.remember_me.data)
                    next = request.args.get('next')
                    if next is None or not next.startswith('/'):
                        next = url_for('home.index')
                    return redirect(next)
                else:
                    flash('用户名或密码无效')
                    return render_template('user/login.html', form=form)
            else:
                return render_template('user/login.html', form=form)
        else:
            return render_template('user/login.html', form=form)


@main.route('/register', methods=['GET', 'POST'])
def register():
    # 用户已登录
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    # 用户未登录
    else:
        error = None
        form = RegistrationForm()
        if request.method == 'POST':
            if form.validate_on_submit():
                new_user = User(
                    username=form.username.data,
                    email=form.email.data,
                    password=form.password.data,
                )
                db.session.add(new_user)
                db.session.commit()
                flash('恭喜, 您已成功注册, 请登录')
                return redirect(url_for('.login'))
            else:
                return render_template('user/register.html', form=form, error=error)
        else:
            return render_template('user/register.html', form=form, error=error)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('您已经退出登录')
    return redirect(url_for('home.index'))


@main.route('/<username>')
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.time_modified.desc()).all()
    return render_template('user/user.html', user=user, posts=posts)


@main.route('/settings', methods=['GET'])
@login_required
def settings():
    user = current_user._get_current_object()
    form_username = SettingUsernameForm()
    form_password = SettingPasswordForm()
    form_signature = SettingSignatureForm()
    form_username.username.data = user.username
    form_signature.signature.data = user.signature
    return render_template(
        'user/settings.html',
        form_username=form_username,
        form_password=form_password,
        form_signature=form_signature,
    )


@main.route('/settings/change_username', methods=['POST'])
@login_required
def change_username():
    user = current_user._get_current_object()
    form_username = SettingUsernameForm()
    if form_username.validate_on_submit():
        user.username = form_username.username.data
        db.session.add(user)
        db.session.commit()
        flash('恭喜, 您已成功修改用户名!')
    return redirect(url_for('.settings'))


@main.route('/settings/change_password', methods=['POST'])
@login_required
def change_password():
    user = current_user._get_current_object()
    form_password = SettingPasswordForm()
    if form_password.validate_on_submit():
        user.password = form_password.password.data
        db.session.add(user)
        db.session.commit()
        flash('恭喜, 您已成功修改密码!')
    return redirect(url_for('.settings'))


@main.route('/settings/signature', methods=['POST'])
@login_required
def change_signature():
    user = current_user._get_current_object()
    form_signature = SettingSignatureForm()
    if form_signature.validate_on_submit():
        user.signature = form_signature.signature.data
        db.session.add(user)
        db.session.commit()
        flash('恭喜, 您已成功修改个性签名!')
    return redirect(url_for('.settings'))

app/templates/post/edit_post.html
{% extends "base.html" %}

{% block page_content %}
<h2 class="ui header">编辑文章</h2>
<div class="ui form">
  <form action="" method="POST">
    {{ form.hidden_tag() }}
    <p>
      {{ form.title.label }}<br>
      {{ form.title(size=32) }}<br>
    </p>
    <p>
      {{ form.body.label }}<br>
      {{ form.body(rows="15") }}<br>
    </p>
    <p>{{ form.submit(class="ui primary button") }}</p>
  </form>
</div>
{% endblock %}

app/templates/post/new_post.html
{% extends "base.html" %}

{% block page_content %}
<div class="ui piled segment">
  <h2 class="ui header">发表新文章</h2>
  <div class="ui form">
    <form action="" method="POST">
      {{ form.hidden_tag() }}
      <p>
        {{ form.title.label }}<br>
        {{ form.title(size=32) }}<br>
      </p>
      <p>
        {{ form.body.label }}<br>
        {{ form.body(rows="15") }}<br>
      </p>
      <p>{{ form.submit(class="ui primary button") }}</p>
    </form>
  </div>
</div>
{% endblock %}

app/templates/post/view_post.html
{% extends "base.html" %}

{% block page_content %}
  <!-- <div class="ui main text container"> -->
  <div class="ui very padded text container tall stacked segment">
    <h2 class="ui header">{{ post.title }}</h2>
    <div class="meta">
      <span>
        <i class="user icon"></i> <a href="{{ url_for('user.profile', username=post.author.username) }}">{{ post.author.username }}</a>
        <i class="calendar icon"></i> {{ moment(post.time_modified).format('L') }}
      </span>
    </div>
    <a href="{{ url_for('post.edit_post', id=post.id) }}">编辑</a>
    <a href="{{ url_for('post.delete_post', id=post.id) }}">删除</a>
    <div class="ui hidden divider"></div>
    <p>{{ post.body }}</p>
  </div>
  <div class="ui hidden divider"></div>
  <div class="ui comments">
    <h3 class="ui dividing header"><i class="icon comments"></i> 评论</h3>
    <form class="ui reply form" action="" method="post">
      {{ form.hidden_tag() }}
      {{ form.body(class="field") }}
      {% for error in form.body.errors %}
        <span style="color: red;">[{{ error }}]</span>
      {% endfor %}
      {{ form.submit(class="ui primary button") }}
    </form>
    <div class="ui hidden divider"></div>
    {% for comment in comments %}
      <div class="comment">
        <a class="avatar">
          <img src="{{ comment.author.gravatar() }}">
        </a>
        <div class="content">
          <a author="author">{{ comment.author.username }}</a>
          <div class="metadata">
            <span class="date">{{ moment(comment.time_created).format('lll') }}</span>
          </div>
          <div class="text">
            <p>{{ comment.body }}</p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}