app/models/user.py
from datetime import datetime
from hashlib import md5
from flask import current_app
from flask_login import UserMixin, AnonymousUserMixin

from app import db, bcrypt, login_manager
from app.models.role import Permission, Role


class User(UserMixin, db.Model):

    __tablename__ = 'Users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    signature = db.Column(db.String(140))
    about_me = db.Column(db.Text())
    avatar_hash = db.Column(db.String(32))
    time_created = db.Column(db.DateTime, default=datetime.utcnow)
    time_modified = db.Column(db.DateTime, default=datetime.utcnow)
    role_id = db.Column(db.Integer, db.ForeignKey('Roles.id'))
    confirmed = db.Column(db.Boolean, default=False)
    posts = db.relationship('Post', backref='author', lazy='dynamic')
    post_comments = db.relationship('PostComment', backref='author', lazy='dynamic')
    post_comment_replies = db.relationship('PostCommentReply', backref='author', lazy='dynamic')
    # thoughts = db.relationship('Thought', backref='author', lazy='dynamic')
    # thought_comments = db.relationship('ThoughtComment', backref='author', lazy='dynamic')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        if self.role is None:
            if self.email == current_app.config['ADMIN']:
                self.role = Role.query.filter_by(name='Administrator').first()
            else:
                self.role = Role.query.filter_by(default=True).first()
        if self.email is not None and self.avatar_hash is None:
            self.avatar_hash = self.gravatar_hash()

    @property
    def password(self):
        raise AttributeError('密码不是一个可读属性')

    @password.setter
    def password(self, password):
        self.password_hash = bcrypt.generate_password_hash(password)

    def verify_password(self, password):
        return bcrypt.check_password_hash(self.password_hash, password)

    def can(self, permission):
        return self.role is not None and self.role.has_permission(permission)

    def is_administrator(self):
        return self.can(Permission.ADMIN)

    def default_avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        u = 'https://cn.gravatar.com/avatar/{}?d=identicon&s={}'.format(digest, size)
        return u

    def gravatar_hash(self):
        return md5(self.email.lower().encode('utf-8')).hexdigest()

    def gravatar(self, size=100, default='identicon', rating='g'):
        url = 'https://cn.gravatar.com/avatar'
        hash = self.avatar_hash or self.gravatar_hash()
        return '{url}/{hash}?s={size}&d={default}&r={rating}'.format(
            url=url,
            hash=hash,
            size=size,
            default=default,
            rating=rating,
        )

    def __repr__(self):
        return '<User {0}>'.format(self.username)


class AnonymousUser(AnonymousUserMixin):

    def can(self, permission):
        return False

    def is_administrator(self):
        return False

app/forms/user.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, BooleanField, SubmitField
from wtforms.validators import ValidationError, DataRequired, Length, Email, EqualTo
from app.models.user import User


class LoginForm(FlaskForm):
    username = StringField('用户名', validators=[DataRequired(message='此项不能为空')])
    password = PasswordField('密码', validators=[DataRequired(message='此项不能为空')])
    remember_me = BooleanField('记住我')
    submit = SubmitField('登录')


class RegistrationForm(FlaskForm):
    username = StringField(
        '用户名',
        validators=[
            DataRequired(message='此项不能为空'),
            Length(2, 32, message='用户名的字符长度必须大于2小于32'),
        ],
    )
    email = StringField(
        '邮箱',
        validators=[
            DataRequired(message='此项不能为空'),
            Email(),
            Length(1, 64, message='用户名的字符长度必须大于1小于64'),
        ],
    )
    password = PasswordField(
        '密码',
        validators=[
            DataRequired(message='此项不能为空'),
            Length(2, 20, message='密码的字符长度必须大于2小于20'),
        ],
    )
    password2 = PasswordField(
        '确认密码',
        validators=[
            DataRequired('此项不能为空'),
            EqualTo('password', message='两次输入的密码必须一致'),
        ],
    )
    submit = SubmitField('注册')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('该用户名已被注册')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('该邮箱已被注册')


class SettingUsernameForm(FlaskForm):
    username = StringField(
        '用户名',
        validators=[
            DataRequired(message='此项不能为空'),
            Length(2, 32, message='用户名的字符长度必须大于2小于32'),
        ],
    )
    submit = SubmitField('提交修改')


class SettingPasswordForm(FlaskForm):
    password = PasswordField(
        '新密码',
        validators=[
            DataRequired(message='此项不能为空'),
            Length(2, 20, message='密码的字符长度必须大于2小于20'),
        ],
    )
    password2 = PasswordField(
        '确认新密码',
        validators=[
            DataRequired('此项不能为空'),
            EqualTo('password', message='两次输入的密码必须一致'),
        ],
    )
    submit = SubmitField('提交修改')


class SettingSignatureForm(FlaskForm):
    signature = TextAreaField(
        '个性签名',
    )
    submit = SubmitField('提交修改')

app/routes/user.py
from flask import (
    render_template,
    redirect,
    url_for,
    request,
    flash,
    Blueprint,
)
from flask_login import (
    current_user,
    login_user,
    logout_user,
    login_required,
)
from app import db
from app.forms.user import (
    LoginForm,
    RegistrationForm,
    SettingUsernameForm,
    SettingPasswordForm,
    SettingSignatureForm,
)
from app.models.user import User
from app.models.post import Post


main = Blueprint('user', __name__)


@main.route('/login', methods=['GET', 'POST'])
def login():
    # 用户已登录
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    # 用户未登录
    else:
        form = LoginForm()
        if request.method == 'POST':
            if form.validate_on_submit():
                user = User.query.filter_by(username=form.username.data).first()
                if user is not None and user.verify_password(form.password.data):
                    login_user(user, remember=form.remember_me.data)
                    next = request.args.get('next')
                    if next is None or not next.startswith('/'):
                        next = url_for('home.index')
                    return redirect(next)
                else:
                    flash('用户名或密码无效')
                    return render_template('user/login.html', form=form)
            else:
                return render_template('user/login.html', form=form)
        else:
            return render_template('user/login.html', form=form)


@main.route('/register', methods=['GET', 'POST'])
def register():
    # 用户已登录
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    # 用户未登录
    else:
        error = None
        form = RegistrationForm()
        if request.method == 'POST':
            if form.validate_on_submit():
                new_user = User(
                    username=form.username.data,
                    email=form.email.data,
                    password=form.password.data,
                )
                db.session.add(new_user)
                db.session.commit()
                flash('恭喜, 您已成功注册, 请登录')
                return redirect(url_for('.login'))
            else:
                return render_template('user/register.html', form=form, error=error)
        else:
            return render_template('user/register.html', form=form, error=error)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('您已经退出登录')
    return redirect(url_for('home.index'))


@main.route('/<username>')
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.time_modified.desc()).all()
    return render_template('user/user.html', user=user, posts=posts)


@main.route('/settings', methods=['GET'])
@login_required
def settings():
    user = current_user._get_current_object()
    form_username = SettingUsernameForm()
    form_password = SettingPasswordForm()
    form_signature = SettingSignatureForm()
    form_username.username.data = user.username
    form_signature.signature.data = user.signature
    return render_template(
        'user/settings.html',
        form_username=form_username,
        form_password=form_password,
        form_signature=form_signature,
    )


@main.route('/settings/change_username', methods=['POST'])
@login_required
def change_username():
    user = current_user._get_current_object()
    form_username = SettingUsernameForm()
    if form_username.validate_on_submit():
        user.username = form_username.username.data
        db.session.add(user)
        db.session.commit()
        flash('恭喜, 您已成功修改用户名!')
    return redirect(url_for('.settings'))


@main.route('/settings/change_password', methods=['POST'])
@login_required
def change_password():
    user = current_user._get_current_object()
    form_password = SettingPasswordForm()
    if form_password.validate_on_submit():
        user.password = form_password.password.data
        db.session.add(user)
        db.session.commit()
        flash('恭喜, 您已成功修改密码!')
    return redirect(url_for('.settings'))


@main.route('/settings/signature', methods=['POST'])
@login_required
def change_signature():
    user = current_user._get_current_object()
    form_signature = SettingSignatureForm()
    if form_signature.validate_on_submit():
        user.signature = form_signature.signature.data
        db.session.add(user)
        db.session.commit()
        flash('恭喜, 您已成功修改个性签名!')
    return redirect(url_for('.settings'))

app/templates/user/login.html
{% extends "base.html" %}

{% block title %}登录{% endblock %}

{% block page_content %}
<div class="ui centered grid">
  <div class="eight wide column">
    {% block messages %}
      {{ super() }}
    {% endblock %}
    <h2 class="ui dividing header">用户登录</h2>
    <div class="ui large form">
      <form action="" method="POST">
          {{ form.hidden_tag() }}
          <div class="field">
            {{ form.username.label }}
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
              {% include '_error.html' %}
            {% endfor %}
          </div>
          <div class="field">
            {{ form.password.label }}
            {{ form.password(size=32) }}
            {% for error in form.username.errors %}
              {% include '_error.html' %}
            {% endfor %}
          </div>
          <div class="field">
            <div class="ui checkbox">
              {{ form.remember_me() }}{{ form.remember_me.label }}
            </div>
          </div>
          {{ form.submit(class="ui primary button") }}
      </form>
    </div>
    <div class="ui hidden divider"></div>
    <div class="field">
      新用户? <a href="{{ url_for('user.register') }}">立即注册</a>
    </div>
  </div>
</div>
{% endblock %}

app/templates/user/profile.html
{% extends "base.html" %}

{% block page_content %}
  {% include '_posts.html' %}
{% endblock %}

app/templates/user/register.html
{% extends "base.html" %}

{% block title %}注册{% endblock %}

{% block page_content %}
<div class="ui centered grid">
  <div class="eight wide column">
    <h2 class="ui dividing header">用户注册</h2>
    <div class="ui large form">
      <form action="" method="POST">
          {{ form.hidden_tag() }}
          <div class="field">
            {{ form.username.label }}
            {{ form.username(size=32) }}
            {% for error in form.username.errors %}
              {% include '_error.html' %}
            {% endfor %}
          </div>
          <div class="field">
            {{ form.email.label }}
            {{ form.email(size=64) }}
            {% for error in form.email.errors %}
              {% include '_error.html' %}
            {% endfor %}
          </div>
          <div class="field">
            {{ form.password.label }}
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
              {% include '_error.html' %}
            {% endfor %}
          </div>
          <div class="field">
            {{ form.password2.label }}
            {{ form.password2(size=32) }}
            {% for error in form.password2.errors %}
              {% include '_error.html' %}
            {% endfor %}
          </div>
          {{ form.submit(class="ui primary button") }}
      </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/user/settings.html
{% extends "base.html" %}

{% block title %}账户设置{% endblock %}

{% block page_content %}
{% block messages %}
  {{ super() }}
{% endblock %}
<div class="ui segment">
  <h2 class="ui dividing header">账户设置</h2>
  <div class="ui items">
    <div class="ui item">
      <div class="ui large form">
        <form action="{{ url_for('user.change_username') }}" method="POST">
            {{ form_username.hidden_tag() }}
            <div class="field">
              {{ form_username.username.label }}
              {{ form_username.username(size=32) }}
              {% for error in form_username.username.errors %}
                {% include '_error.html' %}
              {% endfor %}
            </div>
            {{ form_username.submit(class="ui primary button") }}
        </form>
      </div>
    </div>
    <div class="ui divider"></div>
    <div class="ui item">
      <div class="ui large form">
        <form action="{{ url_for('user.change_password') }}" method="POST">
            {{ form_password.hidden_tag() }}
            <div class="field">
              {{ form_password.password.label }}
              {{ form_password.password(size=32) }}
              {% for error in form_password.password.errors %}
                {% include '_error.html' %}
              {% endfor %}
            </div>
            <div class="field">
              {{ form_password.password2.label }}
              {{ form_password.password2(size=32) }}
              {% for error in form_password.password2.errors %}
                {% include '_error.html' %}
              {% endfor %}
            </div>
            {{ form_password.submit(class="ui primary button") }}
        </form>
      </div>
    </div>
    <div class="ui divider"></div>
    <div class="ui item">
      <div class="ui large form">
        <form action="{{ url_for('user.change_signature') }}" method="POST">
            {{ form_signature.hidden_tag() }}
            <div class="field">
              {{ form_signature.signature.label }}
                {{ form_signature.signature(rows='5', cols='32') }}
              {% for error in form_signature.signature.errors %}
                {% include '_error.html' %}
              {% endfor %}
            </div>
            {{ form_signature.submit(class="ui primary button") }}
        </form>
      </div>
    </div>
  </div>
  <div class="ui hidden divider"></div>
</div>
{% endblock %}

app/templates/user/user.html
{% extends "base.html" %}

{% block title %}{{ user.username }} 的个人主页{% endblock %}

{% block page_content %}
  <h1 class="ui dividing header">{{ user.username }} 的个人主页</h1>
  <div class="ui raised very padded text container segment">
    <div class="ui vertical segment">
      <h2 class="ui header">{{ user.username }} 个人签名</h2>
      <p>{{ user.signature }}</p>
    </div>
    <div class="ui hidden divider"></div>
    <div class="ui vertical segment">
      <h2 class="ui header">{{ user.username }} 的文章</h2>
      {% include '_posts.html' %}
    </div>
  </div>
{% endblock %}