app/models/post.py
from datetime import datetime

from app import db


class Post(db.Model):

    __tablename__ = 'Posts'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(64))
    body = db.Column(db.Text)
    time_created = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    time_modified = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey('Users.id'))
    comments = db.relationship('PostComment', backref='post', lazy='dynamic')

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def __repr__(self):
        return '<Post {0}>'.format(self.title)

app/forms/post.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, BooleanField, SelectField,\
    SubmitField
from wtforms.validators import DataRequired, Length, Email, Regexp


class NewPostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired(), Length(1, 128)])
    body = TextAreaField('正文', validators=[DataRequired()])
    submit = SubmitField('发表文章')


class EditPostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired(), Length(1, 128)])
    body = TextAreaField('正文', validators=[DataRequired()])
    submit = SubmitField('提交修改')

app/routes/post.py
from flask import (
    render_template,
    flash,
    redirect,
    url_for,
    request,
    Blueprint,
)
from flask_login import (
    current_user,
    login_user,
    logout_user,
    login_required,
)
from app import db
from app.forms.post import NewPostForm, EditPostForm
from app.forms.comment import PostCommentForm
from app.models.role import Permission
from app.models.user import User
from app.models.post import Post
from app.models.comment import PostComment


from app.models.role import Permission

main = Blueprint('post', __name__)


# 将 Permission 类加入模板上下文
@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)


@main.route('/<int:id>', methods=['GET', 'POST'])
def view_post(id):
    post = Post.query.get_or_404(id)
    form = PostCommentForm()
    comments = post.comments.order_by(PostComment.time_created.asc())
    if request.method == 'POST':
        if form.validate_on_submit():
            comment = PostComment(
                body=form.body.data,
                post=post,
                author=current_user._get_current_object(),
            )
            db.session.add(comment)
            db.session.commit()
            flash('您已发表评论')
            return redirect(url_for('.view_post', id=id))
    else:
        return render_template('post/view_post.html', id=id, post=post, comments=comments, form=form)


@main.route('/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = NewPostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            post = Post(
                title=form.title.data,
                body=form.title.data,
                author=current_user._get_current_object(),
            )
            db.session.add(post)
            db.session.commit()
            flash('恭喜, 您已成功发表文章!')
            return redirect(url_for('.view_post', id=post.id))
        else:
            flash('您提交的表格有误, 请修改后重新发表!')
            return redirect(url_for('.new_post', form=form))
    else:
        return render_template('post/new_post.html', form=form)


@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_post(id):
    post = Post.query.get_or_404(id)
    form = EditPostForm()
    if request.method == 'POST':
        if form.validate_on_submit():
            post.title = form.title.data
            post.body = form.body.data
            db.session.add(post)
            db.session.commit()
            flash('恭喜, 您已成功修改文章!')
            return redirect(url_for('.view_post', id=post.id))
        else:
            flash('您提交的表格有误, 请修改后重新发表!')
            return redirect(url_for('.edit_post', form=form))
    else:
        form.title.data = post.title
        form.body.data = post.body
        return render_template('post/edit_post.html', form=form)


@main.route('/delete/<int:id>')
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()
    comments = post.comments
    for comment in comments:
        db.session.delete(comment)
    db.session.delete(post)
    db.session.commit()
    return redirect(url_for('home.index'))

app/routes/user.py
from flask import (
    render_template,
    redirect,
    url_for,
    request,
    flash,
    Blueprint,
)
from flask_login import (
    current_user,
    login_user,
    logout_user,
    login_required,
)
from app import db
from app.forms.user import (
    LoginForm,
    RegistrationForm,
    SettingUsernameForm,
    SettingPasswordForm,
    SettingSignatureForm,
)
from app.models.user import User
from app.models.post import Post


main = Blueprint('user', __name__)


@main.route('/login', methods=['GET', 'POST'])
def login():
    # 用户已登录
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    # 用户未登录
    else:
        form = LoginForm()
        if request.method == 'POST':
            if form.validate_on_submit():
                user = User.query.filter_by(username=form.username.data).first()
                if user is not None and user.verify_password(form.password.data):
                    login_user(user, remember=form.remember_me.data)
                    next = request.args.get('next')
                    if next is None or not next.startswith('/'):
                        next = url_for('home.index')
                    return redirect(next)
                else:
                    flash('用户名或密码无效')
                    return render_template('user/login.html', form=form)
            else:
                return render_template('user/login.html', form=form)
        else:
            return render_template('user/login.html', form=form)


@main.route('/register', methods=['GET', 'POST'])
def register():
    # 用户已登录
    if current_user.is_authenticated:
        return redirect(url_for('home.index'))
    # 用户未登录
    else:
        error = None
        form = RegistrationForm()
        if request.method == 'POST':
            if form.validate_on_submit():
                new_user = User(
                    username=form.username.data,
                    email=form.email.data,
                    password=form.password.data,
                )
                db.session.add(new_user)
                db.session.commit()
                flash('恭喜, 您已成功注册, 请登录')
                return redirect(url_for('.login'))
            else:
                return render_template('user/register.html', form=form, error=error)
        else:
            return render_template('user/register.html', form=form, error=error)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    flash('您已经退出登录')
    return redirect(url_for('home.index'))


@main.route('/<username>')
def profile(username):
    user = User.query.filter_by(username=username).first_or_404()
    posts = user.posts.order_by(Post.time_modified.desc()).all()
    return render_template('user/user.html', user=user, posts=posts)


@main.route('/settings', methods=['GET'])
@login_required
def settings():
    user = current_user._get_current_object()
    form_username = SettingUsernameForm()
    form_password = SettingPasswordForm()
    form_signature = SettingSignatureForm()
    form_username.username.data = user.username
    form_signature.signature.data = user.signature
    return render_template(
        'user/settings.html',
        form_username=form_username,
        form_password=form_password,
        form_signature=form_signature,
    )


@main.route('/settings/change_username', methods=['POST'])
@login_required
def change_username():
    user = current_user._get_current_object()
    form_username = SettingUsernameForm()
    if form_username.validate_on_submit():
        user.username = form_username.username.data
        db.session.add(user)
        db.session.commit()
        flash('恭喜, 您已成功修改用户名!')
    return redirect(url_for('.settings'))


@main.route('/settings/change_password', methods=['POST'])
@login_required
def change_password():
    user = current_user._get_current_object()
    form_password = SettingPasswordForm()
    if form_password.validate_on_submit():
        user.password = form_password.password.data
        db.session.add(user)
        db.session.commit()
        flash('恭喜, 您已成功修改密码!')
    return redirect(url_for('.settings'))


@main.route('/settings/signature', methods=['POST'])
@login_required
def change_signature():
    user = current_user._get_current_object()
    form_signature = SettingSignatureForm()
    if form_signature.validate_on_submit():
        user.signature = form_signature.signature.data
        db.session.add(user)
        db.session.commit()
        flash('恭喜, 您已成功修改个性签名!')
    return redirect(url_for('.settings'))

app/templates/_error.html
<div class="ui negative tiny message">
  <i class="close icon"></i>
  <span>{{ error }}</span>
</div>

app/templates/_posts.html
<div class="ui items">
  {% for post in posts %}
    <div class="item" align="left">
      <div class="content">
        <a class="header" href="{{ url_for('post.view_post', id=post.id) }}">{{ post.title }}</a>
        <div class="meta">
          <span>
            <i class="calendar icon"></i> {{ moment(post.time_modified).format('L') }}
            <i class="user icon"></i> <a href="{{ url_for('user.profile', username=post.author.username) }}">{{ post.author.username }}</a>
          </span>
        </div>
        <div class="description" align="justify">
          <p>{{ post.body }}</p>
        </div>
        <div class="extra">
          <a href="{{ url_for('post.view_post', id=post.id) }}"><div class="ui blue right floated button">阅读全文</div></a>
        </div>
      </div>
    </div>
    <div class="ui divider"></div>
  {% endfor %}
</div>

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
  {% block head %}
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    <title>{% block title %}{% endblock %} - 我的博客</title>
    <!-- <title>Fixed Menu Example - Semantic</title> -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/lib/semantic.min.css') }}">

    <style type="text/css">
      body {
        background-color: #FFFFFF;
      }
      .ui.menu .item img.logo {
        margin-right: 1.5em;
      }
      .main.container {
        margin-top: 7em;
      }
      .wireframe {
        margin-top: 2em;
      }
      .ui.footer.segment {
        margin: 5em 0em 0em;
        padding: 5em 0em;
      }
      .Site {
        display: flex;
        min-height: 100vh;
        flex-direction: column;
      }

      .Site-content {
        flex: 1;
      }
    </style>
  {% endblock %}
</head>

<body class="Site">

  <main class="Site-content">
    <div class="ui inverted fixed menu">
      <div class="ui container">
        <a href="{{ url_for('home.index') }}" class="header item">
          <!-- <img class="logo" src="assets/images/logo.png"> -->
          个人博客
        </a>
        <a href="{{ url_for('home.index') }}" class="item"><i class="home icon"></i>主页</a>
        {% if current_user.is_authenticated %}
        <div class="right menu">
          <!-- <div class="ui right aligned category search item">
            <div class="inverted ui transparent icon input">
              <input class="prompt" type="text" placeholder="搜索文章...">
              <i class="inverted search link icon"></i>
            </div>
            <div class="results"></div>
          </div> -->
          <div class="ui simple dropdown item">
            <i class="user icon"></i>个人中心 <i class="dropdown icon"></i>
            <div class="menu">
              <a class="item" href="{{ url_for('post.new_post') }}"><i class="write icon"></i>发表文章</a>
              <a class="item" href="{{ url_for('user.profile', username=current_user.username) }}"><i class="id card icon"></i>个人主页</a>
              <a class="item" href="{{ url_for('user.settings') }}"><i class="settings icon"></i>账户设置</a>
              <a class="item" href="{{ url_for('user.logout') }}"><i class="sign out icon"></i>退出</a>
            </div>
          </div>
        </div>
        {% else %}
        <div class="right menu">
          <a href="{{ url_for('user.login') }}" class="item"><i class="sign in icon"></i>登录</a>
          <a href="{{ url_for('user.register') }}" class="item"><i class="add user icon"></i>注册</a>
        </div>
        {% endif %}
      </div>
    </div>

    {% block content %}
      <div class="ui main text container">
        {% block page_content %}
          {% block messages %}
            {% for message in get_flashed_messages() %}
                <div class="ui floating message">
                  <i class="close icon"></i>
                  <div class="header">
                    {{ message }}
                  </div>
                </div>
            {% endfor %}
          {% endblock %}
        {% endblock %}
      </div>
    {% endblock %}
  </main>

  <footer>
    <div class="ui inverted vertical footer segment">
      <div class="ui center aligned container">
        <div class="six wide centered column">
          <h4 class="ui inverted header">A Blog App</h4>
          <p>Powered by Flask and Semantic UI</p>
        </div>
      </div>
    </div>
  </footer>

  {% block scripts %}
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="../static/js/lib/jquery-3.2.1.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="../static/js/lib/semantic.min.js"></script>
  {{ moment.include_moment() }}
  {{ moment.lang("zh-cn") }}
  <!-- Script for closing messages -->
  <script>
  $('.message .close')
    .on('click', function() {
      $(this)
        .closest('.message')
        .transition('fade')
    })
  </script>
  {% endblock %}

</body>

</html>

app/templates/base1.html
<!DOCTYPE html>
<html lang="en">

  {% block title %}个人博客{% endblock %}

  {% block head %}
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <!-- Bootstrap -->
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
  <!-- <link rel="stylesheet" media="screen" href = "../static/css/lib/bootstrap.min.css"> -->
  <!-- <link rel="stylesheet" media="screen" href = "../static/css/lib/semantic.min.css"> -->
  <link rel="stylesheet" type="text/css" href="../static/css/lib/semantic.min.css">

  <!-- Custom styles for this template -->
  <link href="../static/css/navbar-static-top.css" rel="stylesheet">

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  {% endblock %}

  <body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li role="separator" class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li class="active"><a href="./">Static top <span class="sr-only">(current)</span></a></li>
            <li><a href="../navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    {% block content %}
    <div class="container">
      {% for message in get_flashed_messages() %}
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
      </div>
      {% endfor %}
    </div>
    {% endblock %}

    {% block scripts %}
    <!-- <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script> -->
    <!-- <script src="semantic/dist/semantic.min.js"></script> -->
    <!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script> -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script> -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="../static/js/lib/jquery-3.2.1.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- <script src="../static/js/lib/bootstrap.min.js"></script> -->
    <script src="../static/js/lib/semantic.min.js"></script>
    {% endblock %}
  </body>
</html>